=== aishiguang/jest-bdd-generator/demo/i18n/schema/locale.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://json-schema.org/draft/2020-12/schema",
  "title": "I18n configurations",
  "description": "Digit-Format configurations. see also: https://bytedance.sg.feishu.cn/sheets/RgKHsad7xhxevWtysE4l4YUfgNd",
  "type": "object",
  "properties": {
    "name": {
      "description": "abbreviation of the language",
      "type": "string"
    },
    "format": {
      "description": "grouping pattern, where to put ',' and '.'",
      "type": "object",
      "properties": {
        "pattern": {
          "description": ". - The decimal separator placeholder. In a computer program, this gets replaced automatically by the actual symbol used for the decimal point in your locale.  Not a real period ; must be retained!\n - The grouping (thousand) separator placeholder. In a computer program, this gets automatically replaced by the actual grouping separator in your language.  Not a real comma ; must be retained!\n0 - The placeholder for the start of a whole number. In a computer program, this gets replaced by an actual digit (or a zero if there aren't enough digits). N ot a real zero(digit) ; must be retained!\n# - The # symbols are place holders for placements of digits based on positions of digit separator. In a computer program, these would be replaced by actual digits. The main use of # is to show the placement of the ',' (grouping separator).",
          "type": "string"
        },
        "minGroupingDigit": {
          "description": "when to start grouping, with 1000 or 10000",
          "type": "number"
        }
      },
      "required": ["pattern"]
    },

    "proportional": {
      "description": "percent and per-mille",
      "type": "object",
      "properties": {
        "percent": {
          "description": "how to display %",
          "type": "string"
        },
        "perMille": {
          "description": "how to display â€°",
          "type": "string"
        }
      },
      "required": ["percent"]
    },

    "currency": {
      "description": "TBD - for ",
      "type": "array",
      "items": {
        "type": "string"
      }
    },

    "compact": {
      "description": "abbreviations for long numbers, i.e. 10000 to 10k",
      "type": "object",
      "patternProperties": {
        "^\\ddigit": {
          "type": "object",
          "properties": {
            "short": {
              "type": "object",
              "properties": {
                "other": {
                  "type": "string"
                },

                "one": {
                  "type": ["string", "null"]
                },

                "two": {
                  "type": ["string", "null"]
                },

                "few": {
                  "type": ["string", "null"]
                },

                "many": {
                  "type": ["string", "null"]
                },

                "zero": {
                  "type": ["string", "null"]
                }
              }
            },

            "long": {
              "type": ["object", "null"],
              "properties": {
                "other": {
                  "type": "string"
                },

                "one": {
                  "type": ["string", "null"]
                },

                "two": {
                  "type": ["string", "null"]
                },

                "few": {
                  "type": ["string", "null"]
                },

                "many": {
                  "type": ["string", "null"]
                },

                "zero": {
                  "type": ["string", "null"]
                }
              }
            }
          }
        }
      }
    },
    "range": {
      "type": "object",
      "properties": {
        "between": {
          "type": "object",
          "properties": {
            "short": {
              "type": "string"
            },
            "long": {
              "type": "string"
            }
          },
          "required": ["short"]
        },

        "approximately": {
          "type": "object",
          "properties": {
            "short": {
              "type": "string"
            },
            "long": {
              "type": "string"
            }
          },
          "required": ["short"]
        },

        "atLeast": {
          "type": "object",
          "properties": {
            "short": {
              "type": "string"
            },
            "long": {
              "type": "string"
            }
          },
          "required": ["short"]
        },

        "atMost": {
          "type": "object",
          "properties": {
            "short": {
              "type": "string"
            },
            "long": {
              "type": "string"
            }
          },
          "required": ["short"]
        }
      },
      "required": ["between", "approximately", "atLeast", "atMost"]
    },
    "scientific": {
      "type": "string"
    }
  },
  "required": ["name", "format", "proportional", "compact", "range", "scientific"]
}

=== aishiguang/jest-bdd-generator/demo/i18n/km.json
{
  "name": "km",
  "format": { "pattern": "#,##0.###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#E0",
  "compact": {
    "4digit": { "long": { "other": "0 ពាន់" }, "short": { "other": "0 ពាន់" } },
    "7digit": { "long": { "other": "0 លាន" }, "short": { "other": "0 លាន" } },
    "10digit": { "long": { "other": "0 ប៊ីលាន" }, "short": { "other": "0 ប៊ីលាន" } },
    "13digit": { "long": { "other": "0 ទ្រីលាន" }, "short": { "other": "0 ទ្រីលាន" } }
  },
  "range": {
    "between": { "short": "{0}–{1}", "long": "{0} ទៅ {1}" },
    "approximately": { "short": "~{0}", "long": "ប្រហែល {0} ដង" },
    "atLeast": { "short": "{0}+", "long": "យ៉ាងតិច {0}" },
    "atMost": { "short": "≤{0}", "long": "យ៉ាងច្រើន {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/uz.json
{
  "name": "uz",
  "format": { "pattern": "# ##0,###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#E0",
  "compact": {
    "4digit": { "long": { "one": "0 ming", "other": "0 ming" }, "short": { "one": "0 ming", "other": "0 ming" } },
    "7digit": { "long": { "one": "0 million", "other": "0 million" }, "short": { "one": "0 mln", "other": "0 mln" } },
    "10digit": {
      "long": { "one": "0 milliard", "other": "0 milliard" },
      "short": { "one": "0 mlrd", "other": "0 mlrd" }
    },
    "13digit": {
      "long": { "one": "0 trillion", "other": "0 trillion" },
      "short": { "one": "0 trln", "other": "0 trln" }
    }
  },
  "range": {
    "between": { "short": "{0}–{1}", "long": "{0} dan {1} gacha" },
    "approximately": { "short": "~{0}", "long": "taxminan {0}" },
    "atLeast": { "short": "≥{0}", "long": "kamida {0}" },
    "atMost": { "short": "≤{0}", "long": "koʻpi bilan {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/lt.json
{
  "name": "lt",
  "format": { "pattern": "## ##0,###" },
  "proportional": { "percent": "{0} %", "perMille": "{0} ‰" },
  "currency": [""],
  "scientific": "#×10^0",
  "compact": {
    "4digit": {
      "long": { "one": "0 tūkstantis", "few": "0 tūkstančiai", "many": "0 tūkstančio", "other": "0 tūkstančių" },
      "short": { "one": "0 tūkst.", "few": "0 tūkst.", "many": "0 tūkst.", "other": "0 tūkst." }
    },
    "7digit": {
      "long": { "one": "0 milijonas", "few": "0 milijonai", "many": "0 milijono", "other": "0 milijonų" },
      "short": { "one": "0 mln.", "few": "0 mln.", "many": "0 mln.", "other": "0 mln." }
    },
    "10digit": {
      "long": { "one": "0 milijardas", "few": "0 milijardai", "many": "0 milijardo", "other": "0 milijardų" },
      "short": { "one": "0 mlrd.", "few": "0 mlrd.", "many": "0 mlrd.", "other": "0 mlrd." }
    },
    "13digit": {
      "long": { "one": "0 trilijonas", "few": "0 trilijonai", "many": "0 trilijono", "other": "0 trilijonų" },
      "short": { "one": "0 trln.", "few": "0 trln.", "many": "0 trln.", "other": "0 trln." }
    }
  },
  "range": {
    "between": { "short": "{0}–{1}", "long": "Nuo {0} iki {1}" },
    "approximately": { "short": "~{0}", "long": "maždaug {0}" },
    "atLeast": { "short": "≥{0}", "long": "bent {0}" },
    "atMost": { "short": "≤{0}", "long": "daugiausia {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/sl.json
{
  "name": "sl",
  "format": { "pattern": "#.##0,###" },
  "proportional": { "percent": "{0} %", "perMille": "{0} ‰" },
  "currency": [""],
  "scientific": "#e0",
  "compact": {
    "4digit": {
      "long": { "one": "0 tisoč", "two": "0 tisoč", "few": "0 tisoč", "other": "0 tisoč" },
      "short": { "one": "0 tis.", "two": "0 tis.", "few": "0 tis.", "other": "0 tis." }
    },
    "7digit": {
      "long": { "one": "0 milijon", "two": "0 milijona", "few": "0 milijone", "other": "0 milijonov" },
      "short": { "one": "0 mio.", "two": "0 mio.", "few": "0 mio.", "other": "0 mio." }
    },
    "10digit": {
      "long": { "one": "0 milijarda", "two": "0 milijardi", "few": "0 milijarde", "other": "0 milijard" },
      "short": { "one": "0 mrd.", "two": "0 mrd.", "few": "0 mrd.", "other": "0 mrd." }
    },
    "13digit": {
      "long": { "one": "0 bilijon", "two": "0 bilijona", "few": "0 bilijoni", "other": "0 bilijonov" },
      "short": { "one": "0 bil.", "two": "0 bil.", "few": "0 bil.", "other": "0 bil." }
    }
  },
  "range": {
    "between": { "short": "{0}–{1}", "long": "{0} do {1}" },
    "approximately": { "short": "~ {0}", "long": "okrog {0}" },
    "atLeast": { "short": "{0}+", "long": "vsaj {0}" },
    "atMost": { "short": "≤ {0}", "long": "največ {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/zh-Hant.json
{
  "name": "zh-Hant",
  "format": { "pattern": "#,##0.###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#E0",
  "compact": {
    "5digit": { "long": { "other": "0 萬" }, "short": { "other": "0 萬" } },
    "9digit": { "long": { "other": "0 億" }, "short": { "other": "0 億" } },
    "13digit": { "long": { "other": "0兆" }, "short": { "other": "0 兆" } }
  },
  "range": {
    "between": { "short": "{0}-{1}", "long": "{0} 至 {1}" },
    "approximately": { "short": "~{0}", "long": "約 {0}" },
    "atLeast": { "short": "{0}+", "long": "最少 {0}" },
    "atMost": { "short": "≤{0}", "long": "最多 {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/et.json
{
  "name": "et",
  "format": { "pattern": "## ##0,###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#×10^0",
  "compact": {
    "4digit": { "long": { "one": "tuhat;", "other": "0 tuhat" } },
    "7digit": {
      "long": { "one": "miljon;-0 miljon", "other": "0 miljonit" },
      "short": { "one": "0 mln", "other": "0 mln" }
    },
    "10digit": {
      "long": { "one": "miljard;-0 miljard", "other": "0 miljardit" },
      "short": { "one": "0 mld", "other": "0 mld" }
    },
    "13digit": {
      "long": { "one": "triljon;-0 triljon", "other": "0 triljonit" },
      "short": { "one": "0 trln", "other": "0 trln" }
    }
  },
  "range": {
    "between": { "short": "{0}‒{1}", "long": "{0} kuni {1}" },
    "approximately": { "short": "~ {0}", "long": "umbes {0}" },
    "atLeast": { "short": "≥{0}", "long": "vähemalt {0}" },
    "atMost": { "short": "≤ {0}", "long": "kuni {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/vi.json
{
  "name": "vi",
  "format": { "pattern": "#.##0,###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#E0",
  "compact": {
    "4digit": { "long": { "other": "0 nghìn" }, "short": { "other": "0 N" } },
    "7digit": { "long": { "other": "0 triệu" }, "short": { "other": "0 Tr" } },
    "10digit": { "long": { "other": "0 tỷ" }, "short": { "other": "0 T" } },
    "13digit": { "long": { "other": "0 nghìn tỷ" }, "short": { "other": "0 NT" } }
  },
  "range": {
    "between": { "short": "{0}-{1}", "long": "{0} đến {1}" },
    "approximately": { "short": "~{0}", "long": "khoảng {0}" },
    "atLeast": { "short": "{0}+", "long": "tối thiểu {0}" },
    "atMost": { "short": "≤{0}", "long": "tối đa {0}" }
  }
}

=== aishiguang/jest-bdd-generator/demo/i18n/it.json
{
  "name": "it",
  "format": { "pattern": "##.##0,###" },
  "proportional": { "percent": "{0}%", "perMille": "{0}‰" },
  "currency": [""],
  "scientific": "#x10^0",
  "compact": {
    "4digit": { "long": { "one": "mille;", "other": "0 mila" } },
    "7digit": { "long": { "one": "0 milione", "other": "0 milioni" }, "short": { "one": "0 Mln", "other": "0 Mln" } },
    "10digit": {
      "long": { "one": "0 miliardo", "other": "0 miliardi" },
      "short": { "one": "0 Mrd", "other": "0 Mrd" }
    },
    "13digit": { "long": { "one": "0 bilione", "other": "0 bilioni" }, "short": { "one": "0 Bln", "other": "0 Bln" } }
  },
  "range": {
    "between": { "short": "{0}-{1}", "long": "da {0} a {1}" },
    "approximately": { "short": "~{0}", "long": "circa {0}" },
    "atLeast": { "short": "≥{0}", "long": "almeno {0}" },
    "atMost": { "short": "≤{0}", "long": "al massimo {0}" }
  }
}
